import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const cards = [
  // ═══════════════════════════════════════
  // EXPERIAN BUREAU CARDS
  // ═══════════════════════════════════════

  {
    cardName: "Chase Ink Business Unlimited",
    bankName: "Chase",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "chase_experian",
    applyAlone: false,
    stackingOrder: 1,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Client typically needs a relationship with bank or have been building business credit. CHASE HACK: If you have a private banking relationship with Chase, use your referral link — client will get minimum $20k. Deposit $5-10k into account, let sit for 30 days with small $20-30 transactions week to week.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 575000,
    sweetBizRevenueMax: 800000,
    sweetPersonalIncomeMin: 140000,
    sweetPersonalIncomeMax: 300000,
    sweetMonthlySpend: 50000,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: true,
    zeroAprMonths: 12,
    typicalLimitMin: 20000,
    typicalLimitMax: 50000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "FREEZE TRANSUNION before applying. Chase private banking referral link = minimum $20k approval. Submit 2 apps at same time with RM — tell them to separate business expenses.",
    applicationUrl: "https://creditcards.chase.com/business-credit-cards/ink/unlimited",
    notes: "Get approved then go for Chase Ink Cash next. Second card will be approved using same numbers.",
  },
  {
    cardName: "Chase Ink Business Cash",
    bankName: "Chase",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "chase_experian",
    applyAlone: false,
    stackingOrder: 2,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Apply after Chase Ink Unlimited approval. Use same numbers as last Chase biz app.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 575000,
    sweetBizRevenueMax: 800000,
    sweetPersonalIncomeMin: 140000,
    sweetPersonalIncomeMax: 300000,
    sweetMonthlySpend: 50000,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: true,
    zeroAprMonths: 12,
    typicalLimitMin: 15000,
    typicalLimitMax: 40000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "Apply after first Chase card approval — second card will be approved. USE SAME NUMBERS AS LAST CHASE BIZ APP. Remove inquiries (Experian call in hack).",
    applicationUrl: "https://creditcards.chase.com/ink-business-credit-cards/customers/ink-cash-back/card-details",
    notes: "Submit both Chase apps at the same time with RM. Reason for 2 apps: tell RM to separate business expenses.",
  },
  {
    cardName: "American Express Business Blue Cash",
    bankName: "American Express",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "amex_experian",
    applyAlone: false,
    stackingOrder: 3,
    waitDaysAfter: 8,
    requiresRelationship: false,
    relationshipNotes: "Get approved for Platinum, Gold, Plum first, then apply for Blue Cash. May ask for last 3 months of bank statements.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: true,
    documentationType: "stated",
    sweetBizRevenueMin: 275000,
    sweetBizRevenueMax: 320000,
    sweetPersonalIncomeMin: 140000,
    sweetPersonalIncomeMax: 165000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: true,
    zeroAprMonths: 12,
    typicalLimitMin: 15000,
    typicalLimitMax: 35000,
    reportsToPersonal: false,
    alsoOffers: "Amex Gold, Platinum, Plum (all stated income)",
    maxExposure: null,
    hacks: "FREEZE TRANSUNION. Apply as a sequence with Chase applications. HACK: You can go back for the Amex Blue Business Plus after 8 days!",
    applicationUrl: "https://creditcard.americanexpress.com/d/business-bluecash-credit-card/",
    notes: "Blue Cash Business sometimes asks for business bank statements. Amex Gold, Platinum, Plum are all stated income.",
  },
  {
    cardName: "FNBO Business Credit Card",
    bankName: "FNBO",
    bureau: "experian",
    pullType: "soft_initial",
    sequenceGroup: "amex_experian",
    applyAlone: false,
    stackingOrder: 4,
    waitDaysAfter: 0,
    requiresRelationship: false,
    relationshipNotes: "No relationship required. Check prequalification with no hard impact. New York Community Bank and Webstaurant Business Credit Card are also underwritten by FNBO.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 225000,
    sweetBizRevenueMax: 275000,
    sweetPersonalIncomeMin: 95000,
    sweetPersonalIncomeMax: 105000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: true,
    zeroAprMonths: 12,
    typicalLimitMin: 10000,
    typicalLimitMax: 25000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "Check prequalification with no hard impact first. Webstaurant Business Credit Card is easiest FNBO approval — create online account to qualify (not 0% APR though).",
    applicationUrl: "https://www.firstbankcard.com/lynx/#/business/company",
    notes: "Apply in sequence with Amex and Chase.",
  },
  {
    cardName: "PNC Bank Business Credit Card",
    bankName: "PNC Bank",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 5,
    waitDaysAfter: 30,
    requiresRelationship: true,
    relationshipNotes: "Client must create bank relationship. Put solid deposit in the bank. Let sit for 30 days. Same process as Chase. Can call in and do the application over the phone.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 275000,
    sweetBizRevenueMax: 320000,
    sweetPersonalIncomeMin: 140000,
    sweetPersonalIncomeMax: 165000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 15000,
    typicalLimitMax: 30000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "You can call in and do the application over the phone.",
    applicationUrl: "https://www.pnc.com/en/small-business/borrowing/business-credit-cards/pnc-visa-business-credit-card.html",
    notes: "Deposit, wait 30 days with small transactions, then apply.",
  },
  {
    cardName: "Navy Federal Business Credit Card",
    bankName: "Navy Federal",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 6,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Open Navy Federal biz account with $250 and then apply for credit card right away.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: null,
    sweetBizRevenueMax: 1000000,
    sweetPersonalIncomeMin: 160000,
    sweetPersonalIncomeMax: null,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 10000,
    typicalLimitMax: 25000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "Doesn't ask for biz revenue. Put biz revenue under 1 million. Remove inquiries (Experian call in hack).",
    applicationUrl: "https://www.navyfederal.org/loans-cards/credit-cards.html",
    notes: "Personal income $160K+. Doesn't ask for biz revenue.",
  },
  {
    cardName: "PayPal Business Mastercard",
    bankName: "PayPal",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 7,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Create Business account with PayPal first, then apply for business credit card.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 100000,
    sweetBizRevenueMax: 250000,
    sweetPersonalIncomeMin: 100000,
    sweetPersonalIncomeMax: 125000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 10000,
    typicalLimitMax: 25000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "Professional and Technical Services / Retail are business types that have been hitting higher limits. Revenue is a drop down box selection.",
    applicationUrl: "",
    notes: "Not 0% APR.",
  },
  {
    cardName: "Service Credit Union Business Card",
    bankName: "Service Credit Union",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 8,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Open personal account first.",
    minBusinessAge: "2 years",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 180000,
    sweetBizRevenueMax: 210000,
    sweetPersonalIncomeMin: 40000,
    sweetPersonalIncomeMax: null,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 5000,
    typicalLimitMax: 15000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "They will potentially ask for pay stubs. Remove inquiries (Experian call in hack).",
    applicationUrl: "",
    notes: "Personal W2 income should be $40k+ when applying. Business must have 2 years history.",
  },
  {
    cardName: "Bethpage Business Credit Card",
    bankName: "Bethpage FCU",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 9,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Open up account with $100 on deposit. Apply for credit card in branch.",
    minBusinessAge: "",
    requiresInBranch: true,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 180000,
    sweetBizRevenueMax: 220000,
    sweetPersonalIncomeMin: 89000,
    sweetPersonalIncomeMax: 94000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 5000,
    typicalLimitMax: 20000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "",
    applicationUrl: "",
    notes: "Apply in branch.",
  },
  {
    cardName: "US Bank Business Credit Card & LOC",
    bankName: "US Bank",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 10,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Go in branch. Have client build relationship. Deposit $5-10k into account. Apply with banker for in house approval.",
    minBusinessAge: "seasoned",
    requiresInBranch: true,
    requiresTaxReturns: true,
    requiresBankStatements: false,
    documentationType: "documented",
    sweetBizRevenueMin: 325000,
    sweetBizRevenueMax: 375000,
    sweetPersonalIncomeMin: 135000,
    sweetPersonalIncomeMax: 175000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 15000,
    typicalLimitMax: 50000,
    reportsToPersonal: false,
    alsoOffers: "line_of_credit,credit_card",
    maxExposure: null,
    hacks: "Pulls Experian and/or Equifax. Best for client business to be seasoned and have tax returns.",
    applicationUrl: "",
    notes: "LINE OF CREDIT AND CREDIT CARD available. Apply in branch with banker.",
  },
  {
    cardName: "TD Bank Business Credit Card & LOC",
    bankName: "TD Bank",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 11,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Deposit $5-10k when open and apply for line of credit with banker. Let them know you filed your taxes.",
    minBusinessAge: "",
    requiresInBranch: true,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "non_doc",
    sweetBizRevenueMin: null,
    sweetBizRevenueMax: null,
    sweetPersonalIncomeMin: null,
    sweetPersonalIncomeMax: null,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 25000,
    typicalLimitMax: 100000,
    reportsToPersonal: true,
    alsoOffers: "line_of_credit,credit_card",
    maxExposure: 100000,
    hacks: "REPORTS TO PERSONAL! NON-DOC! Can get up to $100k line of credit. Go $25-35k on LOC and apply for credit card as well. HACK: $25k biz LOC for brand new LLCs under a year old! Direct bank relationship available.",
    applicationUrl: "",
    notes: "Can get up to $100k line of credit. Go $25-35k on the LOC and apply for the credit card as well.",
  },
  {
    cardName: "Valley National Bank Business Card & LOC",
    bankName: "Valley National Bank",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 12,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Open biz bank account. Apply in branch.",
    minBusinessAge: "2 years for LOC",
    requiresInBranch: true,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "non_doc",
    sweetBizRevenueMin: 375000,
    sweetBizRevenueMax: 425000,
    sweetPersonalIncomeMin: 150000,
    sweetPersonalIncomeMax: 175000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 25000,
    typicalLimitMax: 100000,
    reportsToPersonal: false,
    alsoOffers: "line_of_credit,credit_card",
    maxExposure: 100000,
    hacks: "Remove inquiry after application. Non-doc exposure up to $100k!",
    applicationUrl: "",
    notes: "Biz credit card and Line of credit. Biz has to be 2 years old for LOC.",
  },
  {
    cardName: "M&T Bank Business Card & LOC",
    bankName: "M&T Bank",
    bureau: "experian",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 13,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Open biz bank account. Apply in branch.",
    minBusinessAge: "2 years for LOC",
    requiresInBranch: true,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "non_doc",
    sweetBizRevenueMin: 375000,
    sweetBizRevenueMax: 425000,
    sweetPersonalIncomeMin: 150000,
    sweetPersonalIncomeMax: 175000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 25000,
    typicalLimitMax: 100000,
    reportsToPersonal: false,
    alsoOffers: "line_of_credit,credit_card",
    maxExposure: 100000,
    hacks: "Remove inquiry after application! Non-doc exposure up to $100k!",
    applicationUrl: "",
    notes: "Biz credit card and Line of credit. Biz has to be 2 years old for LOC.",
  },

  // ═══════════════════════════════════════
  // EQUIFAX BUREAU CARDS
  // ═══════════════════════════════════════

  {
    cardName: "KeyBank Business Credit Card & LOC",
    bankName: "KeyBank",
    bureau: "equifax",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 1,
    waitDaysAfter: 30,
    requiresRelationship: true,
    relationshipNotes: "Go to branch to build relationships. Deposit $5-10k initial visit. Wait 30 days then apply for credit card and business line of credit.",
    minBusinessAge: "2 years for LOC",
    requiresInBranch: true,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 375000,
    sweetBizRevenueMax: 425000,
    sweetPersonalIncomeMin: 150000,
    sweetPersonalIncomeMax: 225000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 15000,
    typicalLimitMax: 50000,
    reportsToPersonal: false,
    alsoOffers: "line_of_credit,credit_card",
    maxExposure: null,
    hacks: "DIRECT BANK RELATIONSHIP available for NY, NJ clients. Contact directly to lock in biz credit card and LOC.",
    applicationUrl: "",
    notes: "Apply for credit card AND business line of credit. 2 years in business required for LOC.",
  },
  {
    cardName: "Citizens Bank Business Credit Card & LOC",
    bankName: "Citizens Bank",
    bureau: "equifax",
    pullType: "soft",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 2,
    waitDaysAfter: 0,
    requiresRelationship: false,
    relationshipNotes: "Direct bank relationship established.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: true,
    documentationType: "stated",
    sweetBizRevenueMin: 375000,
    sweetBizRevenueMax: null,
    sweetPersonalIncomeMin: 95000,
    sweetPersonalIncomeMax: 135000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 10000,
    typicalLimitMax: 35000,
    reportsToPersonal: false,
    alsoOffers: "line_of_credit",
    maxExposure: null,
    hacks: "SOFT PULL Equifax! Also go for line of credit. Must be able to support stated income with bank statements.",
    applicationUrl: "",
    notes: "Soft pull Equifax. Asks for business bank statements. Direct bank relationship available.",
  },
  {
    cardName: "Truist Bank Business Credit Card",
    bankName: "Truist Bank",
    bureau: "equifax",
    pullType: "hard",
    sequenceGroup: "truist_equifax",
    applyAlone: false,
    stackingOrder: 3,
    waitDaysAfter: 0,
    requiresRelationship: false,
    relationshipNotes: "Regional bank — check if they are in your area. Apply for 2 personal cards first, then go for 1 business credit card.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 225000,
    sweetBizRevenueMax: 300000,
    sweetPersonalIncomeMin: 95000,
    sweetPersonalIncomeMax: 135000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 10000,
    typicalLimitMax: 25000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "Apply for 2 personal cards and then go for 1 business credit card. Business approval is typically lower.",
    applicationUrl: "",
    notes: "Regional bank. Stated income. Business approval typically lower than personal.",
  },
  {
    cardName: "NIH FCU Business Credit Card",
    bankName: "NIH FCU",
    bureau: "equifax",
    pullType: "soft",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 4,
    waitDaysAfter: 0,
    requiresRelationship: false,
    relationshipNotes: "",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: null,
    sweetBizRevenueMax: null,
    sweetPersonalIncomeMin: null,
    sweetPersonalIncomeMax: null,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: null,
    typicalLimitMax: null,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "Soft pull Equifax. Waiting on more data points.",
    applicationUrl: "",
    notes: "Soft pull Equifax. Limited data points available — gathering more intel.",
  },
  {
    cardName: "Marcus by Goldman Sachs Business Credit Card",
    bankName: "Goldman Sachs",
    bureau: "equifax",
    pullType: "soft",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 5,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Establish a relationship prior to applying.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 575000,
    sweetBizRevenueMax: 650000,
    sweetPersonalIncomeMin: 225000,
    sweetPersonalIncomeMax: null,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 20000,
    typicalLimitMax: 50000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "Soft pull Equifax! Establish relationship prior.",
    applicationUrl: "",
    notes: "High income requirements. $575-650K biz revenue, $225K+ personal income.",
  },

  // ═══════════════════════════════════════
  // TRANSUNION BUREAU CARDS
  // ═══════════════════════════════════════

  {
    cardName: "Bank of America Business Rewards Credit Card",
    bankName: "Bank of America",
    bureau: "transunion",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 1,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Establish relationships first.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 300000,
    sweetBizRevenueMax: 350000,
    sweetPersonalIncomeMin: 125000,
    sweetPersonalIncomeMax: 135000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 15000,
    typicalLimitMax: 35000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "",
    applicationUrl: "",
    notes: "Establish relationships first.",
  },
  {
    cardName: "Barclays Aviator Business Credit Card",
    bankName: "Barclays",
    bureau: "transunion",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 2,
    waitDaysAfter: 0,
    requiresRelationship: false,
    relationshipNotes: "Can apply with no relationship.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 150000,
    sweetBizRevenueMax: 180000,
    sweetPersonalIncomeMin: 89000,
    sweetPersonalIncomeMax: 94000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 10000,
    typicalLimitMax: 25000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "",
    applicationUrl: "",
    notes: "Can apply with no relationship. Lowest revenue/income requirements in TU group.",
  },
  {
    cardName: "Teachers Federal Credit Union Business Card",
    bankName: "Teachers FCU",
    bureau: "transunion",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 3,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Establish relationship first.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 150000,
    sweetBizRevenueMax: 180000,
    sweetPersonalIncomeMin: 89000,
    sweetPersonalIncomeMax: 94000,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 5000,
    typicalLimitMax: 20000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "",
    applicationUrl: "",
    notes: "Establish relationship first.",
  },
  {
    cardName: "BHG Business Credit Card",
    bankName: "BHG",
    bureau: "transunion",
    pullType: "hard",
    sequenceGroup: "",
    applyAlone: true,
    stackingOrder: 4,
    waitDaysAfter: 0,
    requiresRelationship: false,
    relationshipNotes: "Can apply for business credit card after loan approval on personal or business with BHG.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "documented",
    sweetBizRevenueMin: null,
    sweetBizRevenueMax: null,
    sweetPersonalIncomeMin: null,
    sweetPersonalIncomeMax: null,
    sweetMonthlySpend: null,
    sweetSavings: null,
    sweetInvestments: null,
    hasZeroApr: false,
    zeroAprMonths: 0,
    typicalLimitMin: 10000,
    typicalLimitMax: 50000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "BHG personal loans do NOT report to personal credit report! Apply for biz credit card after loan approval. Documented loan — they will ask for proof of income via paystub.",
    applicationUrl: "",
    notes: "Income depends on loan amount requested. Documented loan. They will ask for proof of income via paystub.",
  },
  {
    cardName: "Elan Financial Business Credit Cards",
    bankName: "Elan Financial",
    bureau: "transunion",
    pullType: "hard",
    sequenceGroup: "elan_transunion",
    applyAlone: false,
    stackingOrder: 5,
    waitDaysAfter: 0,
    requiresRelationship: true,
    relationshipNotes: "Relationship with bank 5+ years. Webster Bank, Ameris Bank, Pinnacle FCU are all underwritten by Elan Financial Services.",
    minBusinessAge: "",
    requiresInBranch: false,
    requiresTaxReturns: false,
    requiresBankStatements: false,
    documentationType: "stated",
    sweetBizRevenueMin: 575000,
    sweetBizRevenueMax: 800000,
    sweetPersonalIncomeMin: 245000,
    sweetPersonalIncomeMax: 275000,
    sweetMonthlySpend: null,
    sweetSavings: 90000,
    sweetInvestments: 100000,
    hasZeroApr: true,
    zeroAprMonths: 18,
    typicalLimitMin: 15000,
    typicalLimitMax: 25000,
    reportsToPersonal: false,
    alsoOffers: "",
    maxExposure: null,
    hacks: "CAN DOUBLE DIP FOR 2 cards. Go for cards with 0% APR for 18 months. Webster Bank, Ameris Bank, Pinnacle FCU are all underwritten by Elan. Never use whole numbers for stated income. Sometimes may pull Transunion. Saw $20K approvals with: revenue $780k, income $210k, savings $260k, investment $235k.",
    applicationUrl: "",
    notes: "Money in market $100-250k, Money saved $90-120k. Stated income. Relationship with bank 5+ years. Sequence with second round of business card funding.",
  },
];

async function main() {
  console.log("Seeding stacking cards...");

  // Clear existing cards
  await prisma.stackingCard.deleteMany();

  for (const card of cards) {
    await prisma.stackingCard.create({ data: card });
    console.log(`  ✓ ${card.cardName} (${card.bureau})`);
  }

  console.log(`\nSeeded ${cards.length} stacking cards.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
